# Generated by Django 4.2.7 on 2023-11-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default='1998-01-22'),
            preserve_default=False,
        ),
    ]
